<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="CL_AxisMaster" Id="{f408589f-d93f-4ed2-926a-1d5fc7672154}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CL_AxisMaster EXTENDS CL_AxisRobot
var
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();]]></ST>
    </Implementation>
    <Method Name="InitDefect" Id="{66a7c3c9-7aff-4ac1-982c-d54ef8229c1c}">
      <Declaration><![CDATA[METHOD PROTECTED InitDefect : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[sWhichAxis := 'virtual-master';
InitDefect := true;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>